name: subscription_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.19.0
  chopper: ^8.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^29.1.35
  flutter_bloc: ^8.1.6
  uuid: ^4.4.2
  material_dialogs: ^1.1.5
  email_validator: ^3.0.0
  fl_chart: ^0.70.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  currency_converter_pro: ^0.0.7
  webview_flutter: ^4.4.0
  flutter_web_auth_2: ^4.1.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  http: ^1.3.0
  webview_flutter_android: ^4.4.0
  table_calendar: ^3.2.0
  marquee: ^2.3.0
  shared_preferences: ^2.5.3

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  freezed: ^2.4.4
  chopper_generator: ^8.1.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true
