name: subscription_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  chopper: ^8.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^29.1.35
  flutter_bloc: ^8.1.6
  uuid: ^4.4.2
  material_dialogs: ^1.1.5
  email_validator: ^3.0.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  freezed: ^2.4.4
  chopper_generator: ^8.1.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
